---
deployment:
  tasks:
    - export DEPLOYPATH=/home/java2779/public_html/Wildan
    - /bin/cp -r public index.html $DEPLOYPATH
    - /bin/cp -r components $DEPLOYPATH
    - /bin/cp -r assets $DEPLOYPATH